{
    imports = [
        ./cli/bat.nix
        ./cli/eza.nix
        ./cli/fastfetch.nix
        ./cli/fish.nix
        ./gui/foot.nix
        ./gui/fuzzel.nix
        ./cli/fzf.nix
        ./cli/helix.nix
        ./gui/hyprlock.nix
        ./cli/starship.nix
        ./gui/waybar.nix
        ./cli/yazi.nix
        ./cli/zoxide.nix
        ./gui/vsc.nix
        ./gui/ags.nix
    ];
}
