{
    imports = [
        ./bat.nix
        ./eza.nix
        ./fastfetch.nix
        ./fish.nix
        ./foot.nix
        ./fuzzel.nix
        ./fzf.nix
        ./helix.nix
        ./hyprland.nix
        ./hyprlock.nix
        ./starship.nix
        ./waybar.nix
        ./yazi.nix
        ./zoxide.nix
        ./ncmpcpp.nix
        ./vsc.nix
        ./ags.nix
    ];
}
